### ISSUE TITLE
Display OneTimeSetUp in report

### ISSUE THREAD

**Issue by Saureg** [unickq/allure-nunit#14]
Hello!

What you can say about showing up OneTimeSetup in report (I mean display OTS in test case near simple SetUp like at image below)
![img](http://img.parcsis.net/i/aadbdcec78e8b7eb05190b22efec63f5.png)

Also in current realization there is no link between test cases and OTS methods and if OTS fails it doesn't show at a report

**Comment by unickq** [comment]
Need to say that it's impossible to reach results of **SetUp**/**TearDown** methods directly from Test. Same for **OneTime**. This lib uses [Action Attributes Approach](https://github.com/nunit/docs/wiki/Action-Attributes) and can parse test output in order to get **SetUp**/**TearDown** issues. But it can't be done for **OneTimeSetUp/OneTimeTearDown**.

## Release [1.0.4-beta24](https://www.nuget.org/packages/NUnit.Allure/1.0.4-beta24):
- [**OneTime**] Attributes added as steps. No results, not execution time - just a method name.
- Console Output is now an allure attachment - much more readable 😉  
- **AllureExtensions.WrapSetUpTearDownParams** for **SetUp**/**TearDown**/**OneTimeSetUp** - ability to change step name and add its execution time.
- **OneTimeTearDown** is just a step without result 😞 . Obviously if **OneTimeSetUp** is failed there won't be any results at all (Action Attributes Approach) - but it's untrackable for **OneTimeTearDown**
### Example:
```csharp
[TearDown]
public void TearDown()
{
     AllureExtensions.WrapSetUpTearDownParams(() =>
     {
          Thread.Sleep(750);
          Console.WriteLine("Example of wrapped TearDown");
     }, "Custom TearDown name here");
}
```
![screenshot_2](https://user-images.githubusercontent.com/6696821/45221060-f6414780-b2b8-11e8-8d96-a2eb96d41376.png)

**Comment by unickq** [comment]
@Saureg did that work for you?

**Comment by unickq** [comment]
https://github.com/unickq/allure-nunit/releases/tag/1.0.4
